import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const service = fs.readFileSync(path.join(root, 'backend/app/services/budget_service.py'), 'utf8');
const legacy = fs.readFileSync(path.join(root, 'backend/app/services/budget_service_legacy.py'), 'utf8');

assert.match(service, /SOURCE_PROTECTED_EXPENSE_STATUSES = frozenset\(\{"disputed", "refund", "deleted"\}\)/, 'Protected ledger statuses must be explicit');
assert.match(service, /if is_source_protected_expense\(existing\):\s*return existing/, 'Receipt hydration must stop at protected evidence');
assert.match(service, /if expense and is_source_protected_expense\(expense\):\s*return expense/, 'Purchase hydration must stop at protected evidence');
assert.match(service, /not is_source_protected_expense\(row\)/, 'Stale purchase cleanup must retain protected evidence');
assert.match(service, /_SOURCE_STATUS_PRIORITY/, 'Duplicate resolution must be status aware');
assert.match(service, /def _canonical_created_at\(created_at: datetime \| None\) -> float:/, 'Canonical ordering must normalize mixed timestamp awareness');
assert.match(service, /created_at = created_at\.replace\(tzinfo=timezone\.utc\)/, 'Naive database timestamps must be interpreted deterministically');
assert.match(service, /created_at\.astimezone\(timezone\.utc\)\.timestamp\(\)/, 'Aware timestamps must be normalized to UTC');
assert.doesNotMatch(service, /expense\.created_at or datetime\.min/, 'Canonical ordering must not compare naive datetime.min with aware timestamps');
assert.match(service, /keep = min\(rows, key=_expense_canonical_key\)/, 'Canonical duplicate selection must use evidence priority');
assert.match(service, /_merge_source_links\(keep, duplicate\)/, 'Canonical row must retain all source identities');
assert.match(service, /async def _reconcile_budget_line_actuals/, 'Budget actuals must pass through one-expense-one-line reconciliation');
assert.match(service, /budget_actual_projection_mismatch/, 'Budget projection mismatch must fail closed');
assert.match(service, /\[actual-unallocated:/, 'Ambiguous actuals must be represented explicitly instead of duplicated');
assert.match(service, /_legacy\.sync_budget_lines_from_estimate = sync_budget_lines_from_estimate/, 'Legacy estimate projection must use stale-line cleanup');
assert.match(service, /await _reconcile_budget_line_actuals\(db, project_id\)/, 'Every budget refresh must finish with exact actual reconciliation');
assert.match(service, /ROUND_HALF_UP/, 'Financial projection must use explicit cent rounding');
assert.match(service, /def _estimate_amount\(line: EstimateLine\) -> Decimal:/, 'Estimate arithmetic must preserve quantity precision');
assert.match(service, /return _decimal\(line\.quantity_planned\) \* _decimal\(line\.unit_price\)/, 'Quantity and price must multiply before cent rounding');
assert.doesNotMatch(service, /_money\(row\.quantity_planned\)/, 'Physical quantity must never be quantized as currency');
assert.match(service, /async def sync_project_budget_planned/, 'Project planned budget must use the canonical decimal writer');
assert.match(service, /async def apply_change_order_to_budget/, 'Change-order lines must use the canonical decimal writer');
assert.match(service, /_legacy\.sync_project_budget_planned = sync_project_budget_planned/, 'Legacy project plan callers must use the canonical writer');
assert.match(service, /_legacy\.apply_change_order_to_budget = apply_change_order_to_budget/, 'Legacy change-order callers must use the canonical writer');
assert.match(service, /amount = _money\(purchase\.total_amount\)/, 'Purchase totals must use commercial money rounding');
assert.match(service, /_legacy\._dedupe_linked_expenses = _dedupe_linked_expenses/, 'Legacy internal calls must use protected dedupe');
assert.match(service, /_legacy\.refresh_budget_facts = refresh_budget_facts/, 'All legacy callers must use the protected refresh entrypoint');
assert.match(service, /_ORIGINAL_REFRESH_BUDGET_FACTS/, 'Existing source hydration must remain the base implementation');
assert.doesNotMatch(service, /existing\.status = "confirmed" if rec\.fns_verified else "pending_receipt"[\s\S]{0,80}if is_source_protected_expense/, 'Protected check must precede receipt status mutation');
assert.match(legacy, /Expense\.status\.in_\(\("confirmed", "pending_receipt"\)\)/, 'Budget fact aggregation must exclude protected statuses');

console.log('Budget ledger and projection integrity contracts passed');