import assert from 'node:assert/strict';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import {
  isNativeNotificationPlatform,
  shouldScheduleNativeConflictNotification,
} from './nativeNotificationPolicy';

assert.equal(isNativeNotificationPlatform('ios'), true, 'iOS supports native notifications');
assert.equal(isNativeNotificationPlatform('android'), true, 'Android supports native notifications');
assert.equal(isNativeNotificationPlatform('web'), false, 'web must not load native notifications');
assert.equal(isNativeNotificationPlatform('windows'), false, 'unknown platforms fail closed');
assert.equal(shouldScheduleNativeConflictNotification('ios', 2), true);
assert.equal(shouldScheduleNativeConflictNotification('android', 1), true);
assert.equal(shouldScheduleNativeConflictNotification('web', 2), false);
assert.equal(shouldScheduleNativeConflictNotification('ios', 0), false);
assert.equal(shouldScheduleNativeConflictNotification('ios', Number.NaN), false);

const mobileRoot = join(__dirname, '..');
const appConfig = JSON.parse(readFileSync(join(mobileRoot, 'app.json'), 'utf8')) as {
  expo?: {
    extra?: Record<string, unknown>;
    ios?: { infoPlist?: Record<string, unknown> };
    plugins?: unknown[];
  };
  extra?: unknown;
  ios?: unknown;
};

assert.deepEqual(Object.keys(appConfig), ['expo'], 'all config must live in the canonical expo object');
assert.equal(appConfig.extra, undefined, 'root extra would be ignored by Expo');
assert.equal(appConfig.ios, undefined, 'root ios would be ignored by Expo');
assert.equal(appConfig.expo?.extra?.locale, 'ru', 'runtime locale must be embedded');
assert.equal(
  appConfig.expo?.ios?.infoPlist?.CFBundleDevelopmentRegion,
  'ru',
  'iOS development region must be embedded',
);

const notificationPlugin = appConfig.expo?.plugins?.find(
  (plugin) => Array.isArray(plugin) && plugin[0] === 'expo-notifications',
) as [string, Record<string, unknown>] | undefined;
assert.ok(notificationPlugin, 'expo-notifications config plugin must be registered');
assert.equal(
  notificationPlugin?.[1]?.enableBackgroundRemoteNotifications,
  true,
  'background remote notification capability must be generated by the plugin',
);

const layoutSource = readFileSync(join(mobileRoot, 'app/_layout.tsx'), 'utf8');
const nativeSource = readFileSync(join(mobileRoot, 'lib/nativeNotifications.ts'), 'utf8');

assert.ok(
  !layoutSource.includes("from 'expo-notifications'")
    && !layoutSource.includes('from "expo-notifications"'),
  'root layout must never statically import expo-notifications on web',
);
assert.ok(
  layoutSource.includes('installNativeNotificationInteractions'),
  'root layout must use the native capability boundary',
);
assert.ok(
  layoutSource.includes('scheduleNativeSyncConflictNotification'),
  'sync conflict notification must use the native capability boundary',
);
assert.ok(
  nativeSource.includes("await import('expo-notifications')"),
  'native module must be loaded dynamically after the platform guard',
);
assert.ok(
  nativeSource.indexOf('supportsNativeNotifications()')
    < nativeSource.indexOf("await import('expo-notifications')"),
  'platform guard must execute before the native module import',
);
assert.ok(
  !layoutSource.includes("typeof window !== 'undefined') {\n        import('expo-notifications')"),
  'web-online handler must not schedule native notifications',
);

function sourceFiles(directory: string): string[] {
  return readdirSync(directory).flatMap((entry) => {
    if (entry === 'node_modules' || entry === '.expo' || entry === 'dist') return [];
    const path = join(directory, entry);
    const stats = statSync(path);
    if (stats.isDirectory()) return sourceFiles(path);
    return /\.(?:ts|tsx)$/.test(entry) ? [path] : [];
  });
}

const allowedBoundary = 'lib/nativeNotifications.ts';
const scannerTest = 'lib/expoNativeCapabilityIntegrity.test.ts';
const forbiddenPatterns: Array<[string, RegExp]> = [
  ['static expo-notifications import', /(?:from\s+|require\s*\()['"]expo-notifications['"]/],
  ['dynamic expo-notifications import', /import\s*\(\s*['"]expo-notifications['"]\s*\)/],
  ['notification handler API', /\bsetNotificationHandler\s*\(/],
  ['notification category API', /\bsetNotificationCategoryAsync\s*\(/],
  ['notification response listener API', /\baddNotificationResponseReceivedListener\s*\(/],
  ['local notification scheduling API', /\bscheduleNotificationAsync\s*\(/],
  ['push permission API', /\brequestPermissionsAsync\s*\(/],
  ['Expo push token API', /\bgetExpoPushTokenAsync\s*\(/],
];

const violations: string[] = [];
for (const path of sourceFiles(mobileRoot)) {
  const relativePath = relative(mobileRoot, path).replaceAll('\\', '/');
  if (relativePath === allowedBoundary || relativePath === scannerTest) continue;
  const source = readFileSync(path, 'utf8');
  for (const [label, pattern] of forbiddenPatterns) {
    if (pattern.test(source)) violations.push(`${relativePath}: ${label}`);
  }
}
assert.deepEqual(
  violations,
  [],
  `all expo-notifications imports and raw APIs must stay inside ${allowedBoundary}:\n${violations.join('\n')}`,
);

console.log('expoNativeCapabilityIntegrity.test OK');
