"""v14

Revision ID: 14ef20b1cf11
Revises: 
Create Date: 2026-06-27 05:06:32.327240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ef20b1cf11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repair_articles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('read_min', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_articles_category'), 'repair_articles', ['category'], unique=False)
    op.create_index(op.f('ix_repair_articles_slug'), 'repair_articles', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('customer', 'contractor', name='userrole'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('moy_nalog_linked', sa.Boolean(), nullable=False),
    sa.Column('npd_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('renovation_type', sa.String(length=32), nullable=False),
    sa.Column('property_type', sa.String(length=32), nullable=False),
    sa.Column('total_area_sqm', sa.Float(), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('contractor_id', sa.String(length=36), nullable=True),
    sa.Column('budget_planned', sa.Float(), nullable=False),
    sa.Column('budget_spent', sa.Float(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_tokens_user_id'), 'push_tokens', ['user_id'], unique=False)
    op.create_table('app_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('notification_type', sa.Enum('stage_review', 'payment_pending', 'change_order', 'room_change', 'chat_message', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link_path', sa.String(length=255), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_notifications_user_id'), 'app_notifications', ['user_id'], unique=False)
    op.create_table('change_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='changeorderstatus'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('qr_raw', sa.Text(), nullable=True),
    sa.Column('fn', sa.String(length=32), nullable=True),
    sa.Column('fd', sa.String(length=32), nullable=True),
    sa.Column('fns_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('room_type', sa.String(length=32), nullable=True),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.Column('width_m', sa.Float(), nullable=False),
    sa.Column('height_m', sa.Float(), nullable=False),
    sa.Column('openings_sq_m', sa.Float(), nullable=False),
    sa.Column('outlets_count', sa.Integer(), nullable=False),
    sa.Column('switches_count', sa.Integer(), nullable=False),
    sa.Column('plumbing_points', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'active', 'review', 'done', name='stagestatus'), nullable=False),
    sa.Column('percent_complete', sa.Float(), nullable=False),
    sa.Column('payment_amount', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_end', sa.Date(), nullable=True),
    sa.Column('contractor_ready', sa.Boolean(), nullable=False),
    sa.Column('contractor_ready_at', sa.DateTime(), nullable=True),
    sa.Column('customer_accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('author_role', sa.String(length=16), nullable=False),
    sa.Column('message_type', sa.Enum('text', 'photo', 'confirm', 'system', name='chatmessagetype'), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimate_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=True),
    sa.Column('line_type', sa.Enum('material', 'work', name='linetype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity_planned', sa.Float(), nullable=False),
    sa.Column('quantity_actual', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('calc_detail', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('stage_id', sa.String(length=36), nullable=True),
    sa.Column('payment_type', sa.Enum('advance', 'stage', 'material', 'final', name='paymenttype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', name='paymentstatus'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_change_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='roomchangestatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('stage_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('author_role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('stage_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('image_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_photos')
    op.drop_table('stage_comments')
    op.drop_table('room_change_requests')
    op.drop_table('payments')
    op.drop_table('estimate_lines')
    op.drop_table('chat_messages')
    op.drop_table('stages')
    op.drop_table('rooms')
    op.drop_table('receipts')
    op.drop_table('chat_threads')
    op.drop_table('change_orders')
    op.drop_index(op.f('ix_app_notifications_user_id'), table_name='app_notifications')
    op.drop_table('app_notifications')
    op.drop_index(op.f('ix_push_tokens_user_id'), table_name='push_tokens')
    op.drop_table('push_tokens')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_repair_articles_slug'), table_name='repair_articles')
    op.drop_index(op.f('ix_repair_articles_category'), table_name='repair_articles')
    op.drop_table('repair_articles')
    # ### end Alembic commands ###
