#!/usr/bin/env python3
"""Fail closed when backend dependency reproducibility drifts."""

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
WORKFLOWS = ROOT / ".github" / "workflows"
PYTHON_VERSION = "3.12.13"
POETRY_VERSION = "2.4.1"
POETRY_CORE_VERSION = "2.4.0"
TEMP_WORKFLOW = WORKFLOWS / "backend-lock-discovery.yml"


def fail(message: str, errors: list[str]) -> None:
    errors.append(message)


def main() -> int:
    errors: list[str] = []

    pyproject_path = BACKEND / "pyproject.toml"
    lock_path = BACKEND / "poetry.lock"
    python_version_path = BACKEND / ".python-version"

    if not lock_path.is_file():
        fail("backend/poetry.lock is missing", errors)
    if not python_version_path.is_file():
        fail("backend/.python-version is missing", errors)
    elif python_version_path.read_text(encoding="utf-8").strip() != PYTHON_VERSION:
        fail(f"backend/.python-version must be exactly {PYTHON_VERSION}", errors)

    pyproject = pyproject_path.read_text(encoding="utf-8")
    required_pyproject_fragments = (
        f'python = ">={PYTHON_VERSION},<3.13"',
        f'requires = ["poetry-core=={POETRY_CORE_VERSION}"]',
        'fpdf2 = "2.8.7"',
    )
    for fragment in required_pyproject_fragments:
        if fragment not in pyproject:
            fail(f"backend/pyproject.toml is missing required contract: {fragment}", errors)

    if TEMP_WORKFLOW.exists():
        fail("temporary write-enabled backend-lock-discovery workflow must not be committed", errors)

    exact_poetry_install = f'python -m pip install --disable-pip-version-check "poetry=={POETRY_VERSION}"'
    for workflow in sorted(WORKFLOWS.glob("*.yml")):
        text = workflow.read_text(encoding="utf-8")
        if "poetry" not in text.lower():
            continue

        relative = workflow.relative_to(ROOT)
        lowered = text.lower()

        if "poetry install" in lowered:
            fail(f"{relative}: use poetry sync, not poetry install", errors)
        if "poetry run pip install" in lowered:
            fail(f"{relative}: ad-hoc pip install inside Poetry env is forbidden", errors)
        if re.search(r"\bpoetry\s+(lock|update)\b", lowered):
            fail(f"{relative}: CI must not resolve or update backend dependencies", errors)
        if re.search(r"(?:^|\n)\s*(?:pip|python\s+-m\s+pip)\s+install[^\n]*\bpoetry\b", text, re.I):
            poetry_install_lines = [
                line.strip()
                for line in text.splitlines()
                if re.search(r"(?:pip|python\s+-m\s+pip)\s+install.*\bpoetry\b", line, re.I)
            ]
            for line in poetry_install_lines:
                if line != exact_poetry_install:
                    fail(
                        f"{relative}: Poetry install must be exactly: {exact_poetry_install}",
                        errors,
                    )
        if "actions/setup-python" in lowered:
            versions = re.findall(r"python-version:\s*[\"']?([^\"'\s]+)", text)
            if not versions:
                fail(f"{relative}: setup-python is missing python-version", errors)
            for version in versions:
                if version != PYTHON_VERSION:
                    fail(
                        f"{relative}: backend Poetry workflow pins Python {version}, expected {PYTHON_VERSION}",
                        errors,
                    )

    if lock_path.is_file():
        lock_text = lock_path.read_text(encoding="utf-8")
        if f'# This file is automatically @generated by Poetry {POETRY_VERSION}' not in lock_text:
            fail(f"backend/poetry.lock must be generated by Poetry {POETRY_VERSION}", errors)
        if 'name = "fpdf2"' not in lock_text:
            fail("backend/poetry.lock does not contain the declared fpdf2 runtime dependency", errors)

    if errors:
        print("Backend dependency integrity FAILED:", file=sys.stderr)
        for error in errors:
            print(f" - {error}", file=sys.stderr)
        return 1

    print(
        "Backend dependency integrity OK: "
        f"Python {PYTHON_VERSION}, Poetry {POETRY_VERSION}, poetry-core {POETRY_CORE_VERSION}, locked graph present."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
